# fly.toml app configuration file generated for dev-nursingchatbot on 2025-06-24T20:55:44+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "dev-nursingchatbot"
primary_region = "sin"

[build]

[env]
PORT = "8080"  # Tells your app the expected port

[experimental]
  cmd = []
  entrypoint = []
  allowed_public_ports = []
  auto_rollback = true

[http_service]
  internal_port = 8080  # Match this to what Uvicorn uses
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
